/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hw4;



/**
 *
 * @author ralph
 */
public class TestForm extends javax.swing.JFrame {

    /**
     * Creates new form TestForm
     */
    public TestForm() {
        initComponents();
        StackHWItem1= new Stack<>();
        StackHWItem2= new Stack<>();
       QueueHwItem1 = new Queue<>();
    }
    private Stack<String> StackHWItem1;  //Stack 1
    private Queue<String> QueueHwItem1;  //Queue
    private Stack<String> StackHWItem2;  // Stack 2
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStack1 = new javax.swing.JTextArea();
        txtQueue = new javax.swing.JTextArea();
        txtStack2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLoadStack = new javax.swing.JButton();
        txtAddToStack = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btn1toQ = new javax.swing.JButton();
        btnqtos2 = new javax.swing.JButton();
        btnEmpty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Stack 1");

        txtStack1.setEditable(false);

        jLabel2.setText("Queue");

        jLabel3.setText("Stack 2");

        btnLoadStack.setText("Add to Stack 1");
        btnLoadStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadStackActionPerformed(evt);
            }
        });

        taOutput.setColumns(20);
        taOutput.setLineWrap(true);
        taOutput.setRows(5);
        taOutput.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taOutput);

        jLabel4.setText("output");

        btn1toQ.setText("Stack 1 to Queue");
        btn1toQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1toQActionPerformed(evt);
            }
        });

        btnqtos2.setText("Queue to Stack 2");
        btnqtos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqtos2ActionPerformed(evt);
            }
        });

        btnEmpty.setText("Empty Stack 2");
        btnEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLoadStack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddToStack, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn1toQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqtos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmpty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtStack1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtStack2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLoadStack)
                            .addComponent(txtAddToStack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1toQ)
                            .addComponent(btnqtos2)
                            .addComponent(btnEmpty))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStack2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtStack1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueueActionPerformed
/**
 * Add item to Stack 1
 * @param evt 
 */
    private void btnLoadStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadStackActionPerformed
        StackHWItem1.Push(txtAddToStack.getText());
        txtStack1.setText(StackHWItem1.toString());
        
    }//GEN-LAST:event_btnLoadStackActionPerformed
/**
 * Move item from stack 1 to queue
 * @param evt 
 */
    private void btn1toQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1toQActionPerformed
        
        try{
        String val =StackHWItem1.Pop();
        QueueHwItem1.Enqueue(val);
        taOutput.setText("Popped " + val+" from Stack 1 and Enqueued to Queue" );
        txtQueue.setText(QueueHwItem1.toString());
        txtStack1.setText(StackHWItem1.toString());
        }catch(java.util.NoSuchElementException nse)
        {
            taOutput.setText("Stack 1 is Empty");
        
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1toQActionPerformed
/**
 * Move item from queue to stack 2
 * @param evt 
 */
    private void btnqtos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqtos2ActionPerformed
       try{
        String val =QueueHwItem1.Dequeue();
        StackHWItem2.Push(val);
        taOutput.setText("Dequeue " + val+" from Queue  and Pushed to Stack 2" );
        txtQueue.setText(QueueHwItem1.toString());
        txtStack2.setText(StackHWItem2.toString());
        }catch(java.util.NoSuchElementException nse)
        {
            taOutput.setText("Queue is Empty");
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnqtos2ActionPerformed
/**
 * Empty Stack 2 to output
 * @param evt 
 */
    private void btnEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptyActionPerformed
        
        boolean hasitems = true;
        StringBuilder sb = new StringBuilder();
        while (hasitems){
            try{
            String val =  StackHWItem2.Pop();
            sb.append("Popped " + val);
            sb.append("\n\r");
            
            }catch(java.util.NoSuchElementException nse)
        {
            hasitems=false;
        
        }
            taOutput.setText(sb.toString());
            
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmptyActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1toQ;
    private javax.swing.JButton btnEmpty;
    private javax.swing.JButton btnLoadStack;
    private javax.swing.JButton btnqtos2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JTextField txtAddToStack;
    private javax.swing.JTextArea txtQueue;
    private javax.swing.JTextArea txtStack1;
    private javax.swing.JTextArea txtStack2;
    // End of variables declaration//GEN-END:variables
}
